version: "3"
services:
  db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: tsbed
      POSTGRES_USER: tsbed
      POSTGRES_PASSWORD: password
    ports:
      - ${DB_PORT:-15432}:5432
    volumes:
      - postgres:/var/lib/postgresql
volumes:
  postgres:
