#!/bin/bash
set -o nounset -o errexit

source "$(dirname "${BASH_SOURCE[0]}")"/container-db-credentials.lib.bash

dry_run_opt=

optspec=":d"
while getopts "${optspec}-:" optchar
do
  case "$optchar" in
    d)
      dry_run_opt=--dry-run
      ;;
    -)
      case "$OPTARG" in
        dry-run)
          dry_run_opt=--dry-run
          ;;
      esac
  esac
done

# shellcheck disable=SC2154
PGPASSWORD="$password" psqldef $dry_run_opt --file=schemafile.sql --host=127.0.0.1 --port="$port" --user="$user" "$db"

npx prisma db pull
npx prisma generate
