#!/bin/bash
set -o nounset -o errexit

while true
do
  if test "$PWD" = /
  then
    exit 1
  fi
  if test -r docker-compose.y*ml
  then
    break
  fi
  cd ..
done

service=db
port=5432

config="$(docker compose config | yq -c)"
# override をしている場合などでは、`docker compose config` では正しく取れないことがある。
# If you are doing override, `docker compose config` may not get it correctly.
# port=$(docker inspect -f "{{(index (index .NetworkSettings.Ports \"${port}/tcp\") 0).HostPort}}" "$(docker compose ps --quiet ${service})")
port=$(jq -r ".services.${service}.ports[] | select(.target == $port) | .published" <<< "$config")
user=$(jq -r ".services.${service}.environment.POSTGRES_USER" <<< "$config")
db="$user"
password=$(jq -r ".services.${service}.environment.POSTGRES_PASSWORD" <<< "$config")

dry_run_opt=

optspec=":d"
while getopts "${optspec}-:" optchar
do
  case "$optchar" in
    d)
      dry_run_opt=--dry-run
      ;;
    -)
      case "$OPTARG" in
        dry-run)
          dry_run_opt=--dry-run
          ;;
      esac
  esac
done

PGPASSWORD="$password" psqldef $dry_run_opt --file=schemafile.sql --host=127.0.0.1 --port="$port" --user="$user" "$db"

npx prisma db pull
npx prisma generate
