#!/bin/bash
set -o nounset -o errexit

source "$(dirname "${BASH_SOURCE[0]}")"/container-db-credentials.lib.bash

# shellcheck disable=SC2154
PGPASSWORD="$password" exec psql --host=127.0.0.1 --port="$port" --username="$user" "$db" "$@"
