#!/bin/bash
set -o nounset -o errexit

service=db
port=5432

while true
do
  if test -r docker-compose.y*ml
  then
    config="$(docker compose config | yq -c)"
    # override をしている場合などでは、`docker compose config` では正しく取れないことがある。
    # If you are doing override, `docker compose config` may not get it correctly.
    # port=$(docker inspect -f "{{(index (index .NetworkSettings.Ports \"${port}/tcp\") 0).HostPort}}" "$(docker compose ps --quiet ${service})")
    port=$(jq -r ".services.${service}.ports[] | select(.target == $port) | .published" <<< "$config")
    user=$(jq -r ".services.${service}.environment.POSTGRES_USER" <<< "$config")
    db="$user"
    password=$(jq -r ".services.${service}.environment.POSTGRES_PASSWORD" <<< "$config")
    PGPASSWORD="$password" exec psql --host=127.0.0.1 --port="$port" --username="$user" "$db" "$@"
    exit 0
  fi
  test "$PWD" = / && exit 1
  cd ..
done
